# makefile para calculadora polaca, versión 1 
# usar tabulador (no espacios) en la línea de comando

simulator	:	Tarea1.o
	gcc	-o	simulator	Tarea1.o

Tarea1.o:	Tarea1.c	Tarea1.h 
	gcc -c Tarea1.c 


clean: 
	rm simulator \ 
	Tarea1.o